apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bluegreen
  annotations:
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"bluegreen-ci:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"bluegreen\")].image"}]'
  name: bluegreen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bluegreen
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: bluegreen
    spec:
      containers:
      - name: bluegreen
        image: ' '
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        env:
        - name: COLOR
          value: green
        resources: {}	
        terminationMessagePath: /dev/termination-log	
